### PR TITLE
Integrated Game Chat

### PR DESCRIPTION
**Pull request by daprof1**
So a few updates .. first edition of the integrated game chat. Includes a playback buffer of 10 lines (can be changed) when people log in. Still need some spam/work filtering for completeness but it does seem to work in all the browsers I tested. Added it through an addition websocket which is applied to an actor through the main application. Probably should be on its own but I'm just happy it works at this point.

Made a few other minor changes. Some of these JS files probably should be hosted from the CDN .. no point in serving them yourself.

Oh .. and edit the chat.js to modify the port if needed .. that could be important :)

### CODE REVIEW

**Comment by daprof1** [comment]
Updated the PR and cleaned a few things

**Comment by patsonluk** [comment]
Thanks again! Sorry I was very busy working on #85  today. But I will look at this PR next for sure1  😸

**Comment by daprof1** [comment]
Updated for all the new lounge PR to ensure no conflicts.

**Comment by patsonluk** [comment]
Probably will look at this PR this weekend since the Lounge is hopefully fixed

And it's long weekend here :)

**Pull request merged**
