### PR TITLE
Instead of setting SQ to 0 when under $0, reduce it by 10% every simulation cycle

### PR DESCRIPTION
**Pull request by StealthHydra179**
But, I'm not sure if this the correct Scala code, I'm not too familiar with scala

In discord people were complaining about setting it to 0 can destroy large airlines

### CODE REVIEW

**Comment by StealthHydra179** [comment]
Converted to draft until I can test it

**Comment by patsonluk** [comment]
Thanks for the code input! :)

The current code would not drop SQ to 0 right the way, it's already bound my the max drop rate as defined in https://github.com/patsonluk/airline/blob/e83700c723aacb5962ebb7a644a965b431b1ceeb/airline-data/src/main/scala/com/patson/AirlineSimulation.scala#L20

**Comment by StealthHydra179** [comment]
Ohhhh I didn't notice it has the max change calculator around lines 570 my bad 😅

**Comment by patsonluk** [comment]
Ah no worries! Please do keep poking at the core simulation code, as there are probably many bugs to be fixed/enhancements to be made.

Not many devs are brave enough to venture into this territory yet, and it would be great if you can offer some help ;)

**Pull request closed without merging**
