### PR TITLE
Added A319,A321

### PR DESCRIPTION
**Pull request by Germanwings**
Done, with picture and code change. 
Greetings,
Germanwings

### CODE REVIEW

**Comment by patsonluk** [comment]
@Germanwings I am still running some local testing.

I have adjusted the parameters a bit (fuel efficiency according to other comparable airplanes). Lifespan (all airbus has 35 year) and some other parameters based on wiki

The images are renamed so they would load properly.

I will wait for your reply before merging it into the game. If you feel certain parameters should be different, please let me know :)

Thanks for the help again

**Comment by Germanwings** [comment]
I am fine with the A319. 3.4 sounds reasonable, but I think that 4.3 might be a bit high since the fuel efficiency is calculated by the amount of passengers*4.3. And that makes the A321 way more unefficient than the A319. I think that it should more like have a factor of *3.6 or so, since the fuel costs are already higher by the larger amount of seats. 

For the price I think that the A319 should cost a little more than the A318, since it has a larger amount of seats. The realistic prices i found of the year 2018 were at 92.3Mil. That is why I think 95 Million is a reasonable price.

**Comment by patsonluk** [comment]
4.3 is for the balance in this game. This part of the game is not that realistic as basically we want bigger airplane to have smaller profit margin (and right now we are using fuel multiplier to achieve that). 4.3 is more in line with other airplanes with similar capacity (i listed the airplane by capacity), having 3.6 will be too powerful and will surely fail the profitability unit test case :(

**Comment by Germanwings** [comment]
Ok, I understand that. But we can overthink and change that for the V2 :D

**Pull request merged**
