### PR TITLE
Mysql Insert optimization for consumption history

### PR DESCRIPTION
**Pull request by daprof1**
Attempt at optimizing DB calls through file IO instead of millions of INSERT calls, also TRUNCATE is more efficient at wiping the table than a mass DELETE FROM

File based will only work when MYSQL is on the same machine as the sim

### CODE REVIEW

**Comment by patsonluk** [comment]
on my PC the original load is around 680 seconds while using a file is 872 seconds. does that make sense? what speed are u seeing on ur dev machine? @daprof1

**Comment by daprof1** [comment]
Before it was 236 seconds for 800k records using inserts, after it was 82 seconds for the file write and 21 seconds for the truncate and file read

**Comment by patsonluk** [comment]
hmm I measured the time spent on the whole function call `updateConsumptions`, with a small modification to allow control whether to use file as a caller.

Then in the simulation, i called the the method twice - once using file load and once not and measured the time of the call. And that's the result i pasted.

The first run was :
No file (old call): 677697 ms 
file (new call): 872664

The second run was:
No file (old call): 915739 ms
file (new call): 1008058 ms

I put a println in the routine that uses file to verify that the right piece of code was executed

**Comment by patsonluk** [comment]
probably has something to do with the HDD type too? u have SSD? :)

**Comment by patsonluk** [comment]
hmm u know what...i will just switch and test on prod...it really doesn't hurt

**Comment by daprof1** [comment]
SSD but inside a VM. Once it was working, I ran the SQL code manually as well from the console to see how long the load was taking and it was pretty quick (usually ~18s range). It's getting it out to a file that seems to be slow link for this method. I want to say BufferedWriter was one of the faster methods but I may be wrong.

**Comment by patsonluk** [comment]
yay changed the query from delete to truncate and it did saves big time! <3

From 90 mins to 65 mins :)

Thanks alot @daprof1 !

I did not merge the DB file change as it seems to vary quite a bit on different hard drive and it seems to make rather minor difference in performance so i would rather favor code simplicity on this one :)

**Pull request closed without merging**
