### PR TITLE
Adds cities to MX, JP, ID, US, LO, OM, CR, PA, BN and PF

### PR DESCRIPTION
**Pull request by matittner**
Merge this when you want to, I just made the PR so it's easier for me to keep track of rep and pop changes.

Pop: 26640282 -> 28092588 (+5.5%)
Chunks before trim: 3851634 -> 3996754 (+3.8%)
airports = 5686 -> 5692 (+6)

Rep
Japan 21.56 -> 23.68
USA 30.38 -> 30.39
Mexico 13.54 -> 14.35
Costa Rica, Panama, Oman, French Polynesia, Brunei and Slovakia  1 -> 1
United Arab Emirates 5.3 -> 6.91
Indonesia 5.13 -> 7.17

### CODE REVIEW

**Comment by patsonluk** [comment]
hehehe this is one big batch!

Probably need to wait after i switch to digitalocean, then the available memory will increase from 8MB to 16! (and 6vCPU too woot woot) for 2/3 of the price

**Comment by matittner** [comment]
> hehehe this is one big batch!
> 
> Probably need to wait after i switch to digitalocean, then the available memory will increase from 8MB to 16! (and 6vCPU too woot woot) for 2/3 of the price

Nothing there is important, add it when you think it's the right time, it's easier for me to keep track of rep changes doing smaller commits so I also went ahead and also made the PR.

Another thing, China is underrepresented for the income.
But it's China. To reach my target of income = coverage %, China would need an increase of 116mi pop.
There are dozens of huge cities missing (8-9mi), but IDK what you think about it.
China has a low income and it is a very competitive market, so I don't think it would break the game balance by adding all that, the problem is the server performance.
I've created a city with 116mi pop and the result was:
Pop: 26640282 ->  31920105 +20%
Chunks before trim: 3851634 -> 4271785 +10%
I would't add all the 116mi pop probably, just the huge missing cities, so I would guess that the increase would be something more like +10% and +5%. 
What do you think? (considering the new server ofc)

**Comment by patsonluk** [comment]
IMHO china is fine, I don't really want to add that much more load at this point :)

The current formula of ur proposed adjustments are based on income level should be equal to coverage %. I think it's a good reference point, but we do not really have to stick too strict to it. 

Are there any outlier countries left on the list? Perhaps we don't really have to make any further changes unless something is way off - I understand some major cities are missing but if the game is rather balanced and it's not too badly below the norm for that country, it's probably Ok as is

My preference would be to work on some smaller countries and make them more "playable" - that probably bring more values to the game compared to adding more pop to already populated markets :)

**Comment by matittner** [comment]
Ok!
I've done what I can to the important ones that had low coverage without updating the master csv.
I don't really care for those small countries since they're never going to be anything more than free +1 rep and all the high income ones are fine, so I'll leave the remaining to whoever wants to add it to the city list.
This was the last commit then, unless you want me to improve a specific country.

For other stuff, adding/checking missing airports is a pain and people always think they should have a higher scale, so I won't touch that.
I may work on the country relationship matrix if I find a "formula" that could be applied to every country.

About the airport expansion, you need to be careful with that "redistribution", I think that if you make the airports upgrade when they reach a X traffic amount, this will probably only further concentrate traffic on these airports, even more on regions like NY or Tokyo where most traffic is in one of the multiple airports for these cities.

**Pull request closed without merging**
