### PR TITLE
Adjustment to passenger models

### PR DESCRIPTION
**Pull request by patsonluk**
## Description
Several issues with existing passenger model:
1. Low income country appear to have unreasonably low demand, especially domestic demand
2. Quality of a flight uses a pretty "flat" models
   - Quality expectation for each link is solely on the Type of the flight (long haul, short haul , domestic /international etc)
   - Perceived price also uses a flat calculation, the benefit of having a high quality link is proportional to the delta from Quality expectation

## Expectation
- Low income country should see significantly more domestic demand
- International link with at least one end as Low income country should see moderately more demand
- Two airlines - one operates lower price, low quality links while another one operates higher price, high quality links. Both in a low income country. The prior should be able to attract more domestic passengers while the later should attract more transit passengers from higher income foreign countries

## Proposal
1. In order to avoid disturbing existing demand for higher  income country. Im thinking to have a introduce a low income threshold (controversial...), any country higher than the threshold will use old calculation ; anything lower will be considered "low income countries".
2. Increase the domestic flight of lower income country by a factor of 2 or 3 (or even more...depends).  The amount of bonus demand might be proportional to how much it deviates from the threshold - has to be careful tho - lower income country should still generate LESS demand . ie: if income(A) < income (B) then domestic_demand(A) < domestic_demand(B) . Need to write test case to verify
3. Similarly, increase the demand flying FROM low income country international flight, but with a smaller factor
4. Quality expectation now also depends on the a passenger's home country income level (on top of flight type and flight class). Lower income countries have lower expectation (hence more perceived price reduction on high quality link and less penalty for low quality one) - in other word, low income country passengers are easier to impress
5. To counter the effect from 3. The "affordable" link price equation will also be adjusted, with low income country giving up on expensive link easier than high income country
6. Super high quality delta (actual quality vs expected quality) should yield reduced benefit - for example if with expected quality 30, perhaps up to link quality 60 will get normal price reduction, but beyond that point would have reduced effect

#### Changes to low income country (before ECON demand -> after ECON demand)
Example India (income 1581)
New Delhi<-> Mumbai : 770 ->5626 
New Delhi<-> Singapore : 258-> 526 

Example Brazil (income 11384)
Rio <-> Brasilia : 1137 ->1391 
Rio<-> New York:  1396-> 1519 

Example China (income 7590) **China receives a -40% adjustment to domestic demand due to highspeed rail network - to make this change less powerful for China**
Guangzhou <-> Wuhan : 6741 -> 7007 
Guangzhou <-> Singapore : 1790 ->2164 

## Other
This is a more realistic and interesting model imo. But this will not be meaningful to user if we don't have a good way to demonstrate the differences

I am going to start another issue for UI changes involved :)

### CODE REVIEW

**Comment by daprof1** [comment]
Looks better on the QA, but I only see my routes. The no demand countries are now working decently and low demand routes are better. I worry about the china nerf tho, perhaps the country list should have some factors on how demand is split
e.g. 
India       0.8 domestic  -  0.15 regional  - 0.05 intercontential 
Burma    0.1 domestic   - 0.8 regional   - 0.1 intercontential
Or perhaps coded demand multipliers .. but something that would allow tweaking of countries without a hardcoded nerf.

**Comment by patsonluk** [comment]
lol there are some hardcode modifiers existing already. Well the China one is not really a big nerf, i mean..after this change it still see very minor boost

**Comment by patsonluk** [comment]
Increased the standard ("suggested") price by 50%.

Reasons:
1. most airlines currently use at least +50% anyway, otherwise route is
usually not profitable. The concern for airlines to have extreme profit
is low as airline usually undercut eachother
2. Simple pricing preference passengers almost never travel due to old
pricing level

Concerns:
Perhaps airlines will get major passenger boost as alot of previously "unaffordable routes" now become affordable - NOT sure what's the percentage tho

I am not too concerned about this due to high level of competition in game, high profit margin is unlikely

**Comment by patsonluk** [comment]
More changes...will type up later...sorry

**Comment by patsonluk** [comment]
Found out more problem with test cases. Going to write more to make sure everything makes sense

**Pull request merged**
