### PR TITLE
Lounge

### PR DESCRIPTION
**Pull request by patsonluk**

### CODE REVIEW

**Comment by daprof1** [comment]
Tested it locally, seems to work okay .. but HUGE performance penalty. Cycle times went from ~240s with the master to ~430s with this branch.

**Comment by patsonluk** [comment]
Ya not looking good...going to let it run for a bit to get more accurate figure. Thanks for checking tho

My first thought is just :
1. Increased passenger chunks/routes to compute 
2. Probably used a bit more memory, and trigger more GC, so the overhead increase is greater than just linear :(
3. Code logic is a bit more complicated, but it's just some extra map lookup...should be quick imho. but who knows...

Trying to increase a bit more memory allocated to the main simulation in the QA instance to see whether it helps

**Comment by patsonluk** [comment]
Kk pretty much narrow down that the extra over head is from the increased amount of "passenger  groups" - which each runs through algorithm to generate a "cost map"

That group jumps from around 41k to 62k after the change.

Adjusted the algorithm to only generate this demand from this new class of "Lounge passengers" if both the from and to airports are size > 4 (increase the business/first class passengers to X 2.5 to offset the mini chunks lost from other airport size < 4 cities)

**Comment by patsonluk** [comment]
Kk after the change the per cycle time is at less than 1300 sec compared to around 1100 sec pre change. I guess it's acceptable.

Merging now

@daprof1 think you mentioned something regarding the simulation optimization? perhaps we can discuss about that next :)

**Comment by daprof1** [comment]
Yup, I saw close to a 50% increase in passenger groups which would explain the increased run time.  Honestly I'm trying to map out some of that stuff currently, along with 50 other things 👍

**Comment by patsonluk** [comment]
ya that part of the code is a bit cryptic... (sigh) bad coding kinda....i had written several other implementation of path finding but haven't really had time to find out which one actually works...

**Comment by daprof1** [comment]
A. A*, D* .. yeah pathfinding can get annoying. Especially parallelized versions (worked on those before *ugh* .. If you want a quick optimization I've got a small branch that I'm trying to update right now that has a decent impact on performance.

**Pull request merged**
