### PR TITLE
Adds cities to France, Belgium, Kuwait, Saudi Arabia, Israel and Canada

### PR DESCRIPTION
**Pull request by matittner**
Updates to Saudi Arabia and Canada would add ~3 rep to each, this would give a boost to our alliance, you may want to hold that until we're a little more ahead of TripleA, or risk looking biased.

The Toronto region of Canada still has a lot of big cities missing, I've decided to not add all as to not give a huge boost in one go, but Canada is still underrepresented comparing to similar income countries.

There are some underrepresented countries where the current data is just too old (decades even), so the cities are there but with a lot less population, we would need to modify the "master" csv or add fictional cities (or just leave it be).
Countries with different city structures like Switzerland and Netherlands are in the same situation.

Specifics cities are in the commit description.

- Saudi Arabia (+ 5.7mi) rep 9.62 -> 12.64
- Kuwait (+ 360k) rep 1 -> 1
- Israel (+ 1.6mi) rep 1 -> 5.41
- Canada (+ 4.7mi) rep 14.87 -> 17.3
- France (+ 870k) rep 16.85 -> 17.18
- Belgium (+ 1.9mi) rep 2.44 -> 7.48

### CODE REVIEW

**Comment by matittner** [comment]
After adding the new cities:
Pop: 25134230 -> 26640282 (+6%)
Chunks before trim: 3670430 -> 3851674 (+5%)
+11 airports (the 6 canadians + dunno)

**Comment by patsonluk** [comment]
Thanks @matittner . Is it possible to get the spreadsheet with country pop coverage again?
 Probably need to look at which countries are the best to work on next

**Comment by patsonluk** [comment]
o wait...this patch adds US cities too hrmmm

**Comment by matittner** [comment]
> o wait...this patch adds US cities too ... If i keep the old logic when US is the standard, then us should stay 30 points which means other countries would see point reduction hrmmm

Oh, I didn't know you had a system like that, I would've asked you before changing it if I knew, sorry.
After adding Boise City some weeks ago the rep was 30.01, and after adding these cities locally it went to 30.44 for me, so I didn't look further into it.

I'll soon create a post on the forum with the pop spreadsheet and a new one where people can add the cities they want. In the meanwhile : [pop coverage spreadsheet](https://docs.google.com/spreadsheets/d/10WzGHugmC1GNWF3IDxA_3M-GQYqBRmD4Sy25RT5vSRY/edit?usp=sharing)

**Pull request merged**
