### PR TITLE
New airplane models merged from Germanwings change

### PR DESCRIPTION
**Pull request by patsonluk**
## Description
Merged the changes from https://github.com/patsonluk/airline/pull/266 to this. Better to have a PR to compare only the airplane changes

### CODE REVIEW

**Comment by patsonluk** [comment]
@Germanwings Thank you for the great work! The data was very clean and consistent! And I <3 then extra manufacturers!

Now I have merged the change with minor change to model spelling and to avoid replacing the old airplanes. I have also assigned the family to each model (mostly according to your change, some extra modifications see below):

Several things that I want to bring to your attention:
1. I noticed you added some of the airplanes that overlap with the existing ones with different values. Though I believe ur stats are likely more accurate, we probably cannot change the existing model due to compatibility issue. I have kept the existing model unchanged but that might mean that we will need to adjust a bit on the airplane stats you provided on capacity
2. We will need to go through the list (now it's sorted on capacity) and adjust the parameters (price, capacity, fuel burn etc). I am thinking the the ER version is supposed to be either a bit less fuel efficient or slightly lower capacity. I noticed that u have already put a slightly higher price tag, which makes sense, but i think cap and fuel efficient should have a very slight diff too. This current commit (https://github.com/patsonluk/airline/pull/274/commits/9fd24d8fd772221b347f6a6d970fd02b80564f2c )contains no parameter adjustment. I will do a first pass of adjustments, then i can compare the 2 and discuss further
3. I have split the 737 family a bit further as that family is simply a bit too large

**Comment by patsonluk** [comment]
First pass of adjustments @Germanwings  https://github.com/patsonluk/airline/pull/274/commits/9e7336fd11007e40a1655ae504ddd5fff9a4e135

**Comment by Germanwings** [comment]
Sure I am fine with you doing some changes and I understand that current stats can't be changed rn, thus we could hold those changes back for v.2 so that every airplane matches. Feel free to perform some adjustments. For the ER Versions, it depends on the planes and I looked that up individually. Some loose seats, some cost more, some do both it really depends.

**Comment by Germanwings** [comment]
737, I would then just create a 737-classic family until the -700 and then a 737-NG Family instead.

**Pull request merged**
