### PR TITLE
Added 4 aircraft (2x MC-21, E195-E2, TU154)

### PR DESCRIPTION
**Pull request by tjmoores**

### CODE REVIEW

**Comment by Germanwings** [comment]
You are missing the pictures m8. Just look at my merge requests and create those pictures like i did in 500x200

**Comment by tjmoores** [comment]
I've done the 2 that are available on norebbo.com now, I guess we just wait for him to make a MC-21 before uploading that.

**Comment by Germanwings** [comment]
I think he won't do the mc-21 in the near future. Just delete those two and then if patson says yes they're ready to merge? xD

**Comment by Germanwings** [comment]
But the E-195-E2 is way to cheap btw.

**Comment by tjmoores** [comment]
Go and tell that to Embraer I guess 🤷‍♂️ it's the right price but I
understand if it needs to be increased to stop it being op

**Comment by patsonluk** [comment]
@tjmoores thanks for the code contribution!

Unfortunately I removed Ikut ones for now (might add in the future) as i found them pretty much overlap with the other TU models 

Some adjustments to the parameters are made, please check the commit comments

**Comment by tjmoores** [comment]
Hey! I agree with the upping of the fuel consumption of the E195, but I think that given one of the main selling points of the Tupolev is the fact it's one of the fastest subsonic planes around it makes more sense to increase the fuel consumption and leave the speed at 950

**Comment by patsonluk** [comment]
ic!

Hm.... TU154 based on wiki has 913km/h max speed, and for the airplane data i usually take cruise speed instead of max speed.

What about 890 max speed with fuel factor of 4.7?

**Comment by patsonluk** [comment]
hmm i do have some inconsistency in my data the B777 does use max speed.

What 913 km/h max speed with 4.8 fuel factor? ;)

**Comment by patsonluk** [comment]
@tjmoores  ^^ ?

**Comment by tjmoores** [comment]
The sources seems really inconsiderate, one says 975 (https://ipfs.io/ipfs/QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco/wiki/Tupolev_Tu-154.html), 2 say 950 (https://www.airliners.net/aircraft-data/tupolev-tu-154/376 & https://www.militaryfactory.com/aircraft/detail.asp?aircraft_id=791#specs) etc - I just took 950 because it was most common, if you look at the airliners one it says 850 is long range cruise, 900 is economical and 950 is max cruise though so I'd say 900 or so is most reasonable

**Comment by patsonluk** [comment]
so r you good with 913 km/h and 4.8 fuel factor? :)

**Comment by tjmoores** [comment]
Yes!

**Pull request merged**
