### PR TITLE
Adds button to restart keeping the balance and assets value

### PR DESCRIPTION
**Pull request by matittner**
It's a simple (balance + asset value).
I didn't look into what you calculate as an asset, but I assume it's airplanes + bases + lounges.
The only thing that changes from a normal restart is the balance assignment, the rest is the same.

This is currently duplicating code, it could be better, but fixing that is beyond my current knowledge.
At least like this, it's easier to make any future changes I guess.

The only problem I can think is if the current asset value isn't enough to go back to a positive balance. The user would be forever stuck with a negative balance. But that's a stupid move and simply restarting the normal way would fix that.

### CODE REVIEW

**Comment by patsonluk** [comment]
Thanks! I will look at it over the weekend in details!

I am wondering if it's a good idea to dissolve the alliance if the leader want to move base. Perhaps we should consider the president system first (or at least give the alliance leader an option to transfer leadership) before removing itself from it due to the reset

**Comment by matittner** [comment]
yeah, I don't see why dissolve the alliance when you restart, but you're doing that in the normal reset so I kept it the same.

**Comment by patsonluk** [comment]
> yeah, I don't see why dissolve the alliance when you restart, but you're doing that in the normal reset so I kept it the same.

I assume bankruptcy is rare for huge alliance, however moving HQs are probably more common.

It is needed to avoid overlapping HQs, otherwise someone can declare bankruptcy and start a overlapping HQ with other members. Unless we put in a check to prevent that

**Comment by matittner** [comment]
oh, true, I didn't think about that possibility.
I think that adding that president system would be a good idea, then we just need to put a warning that if you're the leader the alliance will be disbanded if you restart.

**Comment by patsonluk** [comment]
Deployed a quick change to allow changing leadership, so the alliance leader can at least transfer the leadership before resetting.

Another player submitted another better option #144 with president role so it should make it less painful

**Comment by matittner** [comment]
He made that PR a long time ago, I thought you knew that already.

One player didn't like the option to restart keeping your money, saying that this would destabilize the game performance. TBH he had no idea what he was talking about, he just doesn't like that possibility and is making excuses to make other people hate it too, but w/e, I don't want people complaining about it, so I've closed the PR.
If you ever want to add that option, you can do that in 5min, it's like 3 lines of code.

It seems the server is shitting itself to run the game again, the missing cities won't be added anytime soon, so I've also closed that PR. If you ever want to add that, I think you can merge the closed PR anyway or add it yourself through the sheets I've posted on the forum.

My ISP is fucking with the chat again and I'll be quite busy for the next months, so I'll be mostly inactive ingame, I'll will try to check the forum when I remember to do so, so please keep the forum updated with any future game/server developments!

**Comment by oxford1223334** [comment]
We really need this option to change HQ especially for players that has played this game for a long time. When I first registered, nobody told me that we will have extra slots & cheaper cost in our HQ. I was also 'advised' not to open HQ in a very big airport to avoid big players. But with no limitation, it needs a different kind of strategy. We really REALLY need this option.

**Comment by patsonluk** [comment]
@oxford1223334 @matittner kk im on it  :)

**Pull request closed without merging**
